### Authenticate

POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "hema3.email@gmail.com",
  "password": "HonestMan@1996"
}

### Access Authroized Route

GET http://localhost:3000/auth/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiZW1haWwiOiJoZW1hMy5lbWFpbEBnbWFpbC5jb20iLCJpYXQiOjE3MjM3NTcwOTksImV4cCI6MTcyMzc1NzE1OX0.furYrPQmFema085UGjqstUs_qFvuvZvjiITHrSVbF54