POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "firstName": "Ibrahim",
  "lastName": "Algadi",
  "username": "hema3.email@gmail.com",
  "email": "hema3.email@gmail.com",
  "password": "HonestMan@1996"
}

###
